#!/usr/local/bin/ruby


POP = "../../Data/ME_popinfo.txt"
PLINK = "../../Data/Dataset1/ME_Dataset1"
PERCENT = 0.1
RESULTS = "results"
SCRIPTS = "scripts"



# directory tasks

directory RESULTS

# processing tasks

PRUNED = "ME_Dataset1_LDpruned_#{PERCENT}"

task :ldprune => [RESULTS] do
	sh "./#{SCRIPTS}/LDprune.pl #{PLINK} #{PRUNED} #{PERCENT}"
	sh "mv #{PRUNED}* #{RESULTS}"
end




#cleaning tasks

task :clobber => [RESULTS] do
	sh "rm -r #{RESULTS}"
end

# default

task :default => [:ldprune]
